version: "2"
services:
  db:
    image: "postgres:9.6.2"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:3.2.8"
    command: redis-server
    volumes:
      - "redis:/var/lib/redis/data"

  mailcatcher:
    image: "schickling/mailcatcher:latest"
    ports:
      - "1080:1080"
      - "1025:1025"

  bundler:
    image: busybox
    volumes:
      - /gems

  web:
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
      - mailcatcher
    build: .
    command: ./script/start_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    volumes_from:
      - bundler

  worker:
    depends_on:
      - db
      - redis
      - mailcatcher
    build: .
    command: ./script/start_worker
    volumes:
      - .:/app
    volumes_from:
      - bundler

volumes:
  redis:
  postgres:
