class Micropost < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :user
  has_one_attached :image

  # validations ...............................................................
  validates :user_id, presence: :true
  validates :content, presence: :true, length: { maximum: 140 }

  # callbacks .................................................................
  # scopes ....................................................................
  default_scope -> { order(created_at: :desc) }

  # additional config (i.e. accepts_nested_attribute_for etc...) ..............

  # class methods .............................................................

  # Returns microposts from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end

  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
