class Relationship < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  # validations ...............................................................
  validates :follower_id, presence: :true
  validates :followed_id, presence: :true

  # callbacks .................................................................
  # scopes ....................................................................

  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................

  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
